### ISSUE TITLE
<package> needs updating to <v2> from <v1> but we can't, as it's a symlink

### ISSUE THREAD

**Issue by fregante** [jeffbski/pkglink#4]
I'm not sure if this was caused by pkglink, but npm gave me this issue

```log
npm WARN update-linked node_modules/auto-install needs updating to 1.7.3 from 1.3.11 but we can't, as it's a symlink
```

when trying to update a couple packages via

```sh
npm install --global packagename
```

Could `pkglink` have caused this issue?

I resolved by removing and then reinstalling the package:

```sh
npm remove --global packagename
npm install --global packagename
```

**Comment by jeffbski** [comment]
@bfred-it I don't believe there is any way that pkglink could have caused this issue for you since it never uses symlinks. pkglink only uses hard links so it avoids issues like this one that symlinks can cause.

Also unless you had specifically run pkglink on your /usr/local/lib directory so that it could find the global packages, it wouldn't even know about them. 

I appreciate you reaching out to check though since I would want to know if there were any issues with pkglink. 

I'm glad you figured it out. That is a bit of a cryptic error.
